In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn import metrics
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

In [ ]:
data= pd.read_csv ('log2.csv')
data.head()

,Source Port,Destination Port,NAT Source Port,NAT Destination Port,Action,Bytes,Bytes Sent,Bytes Received,Packets,Elapsed Time (sec),pkts_sent,pkts_received
0,57222,53,54587,53,allow,177,94,83,2,30,1,1
1,56258,3389,56258,3389,allow,4768,1600,3168,19,17,10,9
2,6881,50321,43265,50321,allow,238,118,120,2,1199,1,1
3,50553,3389,50553,3389,allow,3327,1438,1889,15,17,8,7
4,50002,443,45848,443,allow,25358,6778,18580,31,16,13,18

In [ ]:
data['target']=pd.factorize(data['Action'])[0]

In [ ]:
data.head()

,Source Port,Destination Port,NAT Source Port,NAT Destination Port,Action,Bytes,Bytes Sent,Bytes Received,Packets,Elapsed Time (sec),pkts_sent,pkts_received,target
0,57222,53,54587,53,allow,177,94,83,2,30,1,1,0
1,56258,3389,56258,3389,allow,4768,1600,3168,19,17,10,9,0
2,6881,50321,43265,50321,allow,238,118,120,2,1199,1,1,0
3,50553,3389,50553,3389,allow,3327,1438,1889,15,17,8,7,0
4,50002,443,45848,443,allow,25358,6778,18580,31,16,13,18,0

In [ ]:
df=data.drop('Action', axis = 1)
df.head()

,Source Port,Destination Port,NAT Source Port,NAT Destination Port,Bytes,Bytes Sent,Bytes Received,Packets,Elapsed Time (sec),pkts_sent,pkts_received,target
0,57222,53,54587,53,177,94,83,2,30,1,1,0
1,56258,3389,56258,3389,4768,1600,3168,19,17,10,9,0
2,6881,50321,43265,50321,238,118,120,2,1199,1,1,0
3,50553,3389,50553,3389,3327,1438,1889,15,17,8,7,0
4,50002,443,45848,443,25358,6778,18580,31,16,13,18,0

In [ ]:
x=df.drop('target',axis=1)
y=df['target']

In [ ]:
#having test size reflect dataset, test size of 30%
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=5)

In [ ]:
#kernel specifying. 
#There are linear (most common), Gaussian, polynomial, sigmoid, and computable kernel.
#Always try linear first and then try the others (again "trial & error" rule)
#'rbf' stands for radial basis function kernel which is the second best choice after linear

clf=svm.SVC(kernel='rbf')

#train and fit the model
clf.fit(x_train,y_train)

SVC()

In [ ]:
#predict the response
y_pred=clf.predict(x_test)

In [ ]:
print("Accuracy: ", metrics.accuracy_score(y_test,y_pred))

Accuracy:  0.5742115971515768

In [ ]:
#the default average value of both precision and recall is 'binary' which is incorrect here as 
#we have three target labels. When there are multi labels in target, use 'macro' option. 
print("Precision: ",metrics.precision_score(y_test,y_pred, average='macro'))

print("Recall: ",metrics.recall_score(y_test,y_pred, average='macro'))

Precision:  0.1435528992878942
Recall:  0.25

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))